"use client";

import { useEffect, useMemo, useState } from "react";

type Pole = "E" | "I" | "S" | "N" | "T" | "F" | "J" | "P";
type Question = { text: string; pole: Pole; dimension: string };
const labels = ["非常不同意", "不同意", "不确定", "同意", "非常同意"];
const pairs: Record<string, [string, string][]> = {
  EI: [["与人互动后，我通常感觉精力被充满。","安静独处后，我通常感觉精力被充满。"],["我会自然地把想法说出来，与人一起梳理。","我会先在心里想清楚，再决定是否表达。"],["陌生的社交场合常让我感到兴奋。","陌生的社交场合后，我需要一点独处时间恢复。"],["我倾向于边交流边形成观点。","我倾向于独自思考后再形成观点。"],["周围有人时，我更容易进入状态。","不受打扰时，我更容易进入状态。"],["我愿意主动认识新的人。","我更愿意与熟悉的人进行深入交流。"],["我习惯用谈话分享当天的感受。","我习惯先独自消化当天的感受。"],["热闹的活动通常令我感到愉快。","安静而自在的活动通常令我感到愉快。"]],
  SN: [["我会先注意事情具体、可验证的细节。","我会先留意事情背后的意义和可能性。"],["我更信任已有经验能说明什么。","我常会思考不同做法可能带来的新结果。"],["清晰的事实比抽象的设想更能说服我。","一个有启发性的设想常比既有事实更吸引我。"],["我喜欢一步一步把事情做扎实。","我喜欢先看清整体方向，再调整细节。"],["我容易记住实际发生过的细节。","我容易记住由事情引发的联想。"],["我更喜欢明确、直接的表达。","我喜欢能留下想象空间的表达。"],["学习新内容时，我希望先看到具体示例。","学习新内容时，我希望先理解整体概念。"],["我倾向于关注眼前真正需要解决的问题。","我倾向于思考问题未来会如何发展。"]],
  TF: [["做重要决定时，我会先检查它是否合乎逻辑。","做重要决定时，我会先考虑它会如何影响相关的人。"],["讨论中，我重视观点是否一致、清楚。","讨论中，我重视每个人是否被理解和尊重。"],["我愿意直接指出方案中的问题。","我会先考虑指出问题的方式是否合适。"],["公平通常意味着使用相同的原则。","公平通常意味着照顾不同人的具体处境。"],["我倾向于把事实与个人感受分开看。","我会把个人感受视为理解事实的重要部分。"],["面对冲突时，我优先寻找最合理的解决方法。","面对冲突时，我优先维护彼此能够继续沟通的关系。"],["我更在意结论是否经得起推敲。","我更在意结论是否符合自己的价值与关怀。"],["别人通常觉得我在分析问题时很客观。","别人通常觉得我很能体察他人的感受。"]],
  JP: [["提前安排好计划，会让我感到踏实。","保留调整空间，会让我感到自在。"],["我喜欢在开始前明确关键步骤。","我喜欢在过程中根据情况决定下一步。"],["临近截止日期前完成事情，会让我更安心。","有一点时间压力，常能让我更集中。"],["我习惯尽快做出可以执行的决定。","我愿意多保留一些选择再做决定。"],["整洁、有条理的环境有助于我思考。","随手可用、灵活变化的环境让我更自然。"],["旅行前我会倾向于列好主要安排。","旅行时我更享受随遇而安地探索。"],["任务完成后，我喜欢尽快把它从清单中划掉。","我喜欢让任务保持开放，直到有更好的方案。"],["意外的临时变化容易打乱我的节奏。","意外的临时变化常会带来新的可能。"]]
};
const poleMap: Record<string, [Pole, Pole]> = { EI:["E","I"], SN:["S","N"], TF:["T","F"], JP:["J","P"] };
const questions: Question[] = Object.entries(pairs).flatMap(([dimension, rows]) => rows.flatMap(([a,b]) => [{text:a,pole:poleMap[dimension][0],dimension},{text:b,pole:poleMap[dimension][1],dimension}]));
const names: Record<string,string> = { E:"外向",I:"内向",S:"实感",N:"直觉",T:"思考",F:"情感",J:"判断",P:"感知" };
const reflections: Record<Pole,string> = { E:"你可能会在交流、协作与外部行动中获得能量。",I:"你可能更需要独处与安静空间来整理感受和想法。",S:"你可能更信任具体经验、事实与可验证的细节。",N:"你可能更容易被可能性、关联与未来方向吸引。",T:"你可能习惯用一致的原则和逻辑来梳理决定。",F:"你可能会将人的感受、价值与关系纳入决定。",J:"你可能更安心于清晰计划与可执行的安排。",P:"你可能更自在于保留弹性，并随情境调整方向。" };

export default function Home() {
  const saved = typeof window === "undefined" ? null : localStorage.getItem("know-yourself-progress");
  const restored = saved ? JSON.parse(saved) : null;
  const [screen,setScreen] = useState<"home"|"intro"|"quiz"|"result">("home");
  const [index,setIndex] = useState(restored?.index || 0); const [answers,setAnswers] = useState<Record<number,number>>(restored?.answers || {});
  useEffect(()=>{if(screen==="quiz") localStorage.setItem("know-yourself-progress",JSON.stringify({answers,index}));},[answers,index,screen]);
  const result=useMemo(()=>{const sums:Record<Pole,number>={E:0,I:0,S:0,N:0,T:0,F:0,J:0,P:0}; questions.forEach((q,i)=>sums[q.pole]+=answers[i]??0); return Object.entries(poleMap).map(([d,[a,b]])=>({d,a,b,scoreA:sums[a],scoreB:sums[b],winner:sums[a]>=sums[b]?a:b}));},[answers]);
  const finish=()=>{if(Object.keys(answers).length===questions.length)setScreen("result");};
  if(screen==="intro") return <main className="shell"><section className="intro"><p className="eyebrow">开始前</p><h1>请按多数情况下真实的自己作答。</h1><p>没有正确答案。请不要选择“更理想的自己”，而是选择更自然的你。</p><ul><li>共 64 道原创问题，约 8–12 分钟</li><li>可随时返回修改，进度仅保存在你的设备上</li><li>结果仅供自我探索，不是心理诊断</li></ul><button className="primary" onClick={()=>setScreen("quiz")}>我明白了，开始答题 →</button></section></main>;
  if(screen==="quiz"){const q=questions[index];return <main className="shell"><header className="top"><button onClick={()=>setScreen("home")}>← 保存并退出</button><span>认识你自己</span><span>{index+1} / {questions.length}</span></header><div className="progress"><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div><section className="question"><p className="eyebrow">请根据多数情况下真实的自己作答</p><h1>{q.text}</h1><div className="answers">{labels.map((label,value)=><button key={label} className={answers[index]===value+1?"selected":""} onClick={()=>setAnswers({...answers,[index]:value+1})}>{label}</button>)}</div><div className="quiznav"><button disabled={index===0} onClick={()=>setIndex(index-1)}>← 上一题</button>{index===questions.length-1?<button className="next" disabled={Object.keys(answers).length!==questions.length} onClick={finish}>查看结果</button>:<button className="next" disabled={!answers[index]} onClick={()=>setIndex(index+1)}>下一题 →</button>}</div>{index===questions.length-1&&Object.keys(answers).length!==questions.length&&<p className="hint">还有 {questions.length-Object.keys(answers).length} 题未作答，请返回补充。</p>}</section></main>}
  if(screen==="result"){const code=result.map(x=>x.winner).join("");return <main className="shell"><nav><span className="brand">认识你自己</span><button onClick={()=>{localStorage.removeItem("know-yourself-progress");setAnswers({});setIndex(0);setScreen("home")}}>重新探索</button></nav><section className="result"><p className="eyebrow">你的当前偏好组合</p><h1>{code}</h1><p className="lead">这是一张关于你当下偏好的探索地图，而不是固定标签。</p><div className="dimensions">{result.map(x=>{const gap=Math.abs(x.scoreA-x.scoreB);return <article key={x.d}><b>{names[x.winner]}偏好</b><span>{gap<5?"接近，保持开放探索":gap<12?"中等清晰":"较为清晰"}</span><div><i style={{width:`${Math.max(8,Math.min(92,50+(x.scoreA-x.scoreB)*3))}%`}}/></div><small>{names[x.a]}　　{names[x.b]}</small></article>})}</div><section className="notice"><b>给自己的一个提示</b><p>{result.map(x=>reflections[x.winner]).join(" ")}</p></section><section className="notice"><b>深度探索报告，即将推出。</b><p>未来将提供更多情境化反思练习与沟通建议；首期免费结果已包含核心偏好画像。</p></section><p className="hint">结果反映本次自我报告中的偏好，仅供自我探索参考。</p></section></main>}
  return <main className="shell"><nav><span className="brand">认识你自己</span><a href="#about">关于测评</a></nav><section className="hero"><p className="eyebrow">心理类型偏好探索</p><h1>留一点时间，<br/><em>更好地认识自己。</em></h1><p className="lead">通过一组温和、原创的自我探索问题，了解你当下更自然的能量、信息、决策与生活组织偏好。</p><button className="primary" onClick={()=>setScreen("intro")}>开始探索 <span>→</span></button><div className="meta"><span>约 8–12 分钟</span><span>64 道问题</span><span>无需登录</span></div></section><section id="about" className="notice"><b>这不是诊断，也不是标签。</b><p>结果仅反映本次自我报告中的偏好，适合用于自我探索与交流参考。</p></section><footer>© 2026 认识你自己 · 隐私优先，本地保存</footer></main>;
}
